import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const STAGES = ['Order Placed', 'Buyer Associated', 'Processing', 'Packed', 'Shipped', 'Out for Delivery', 'Delivered'];
export default function OrderProgress({ order }) {
    const current = order.currentStage || 1;
    return (_jsxs("div", { className: "bg-white rounded-lg shadow-lg p-6", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h2", { className: "text-2xl font-bold text-gray-800 mb-2", children: "Order Status" }), _jsxs("p", { className: "text-sm text-gray-600", children: ["Order ID: ", _jsx("span", { className: "font-mono", children: order._id })] })] }), _jsxs("div", { className: "mb-8", children: [_jsxs("div", { className: "relative", children: [_jsx("div", { className: "absolute top-5 left-0 right-0 h-1 bg-gray-200" }), _jsx("div", { className: "absolute top-5 left-0 h-1 bg-linear-to-r from-green-500 to-blue-500 transition-all duration-500", style: { width: `${((current - 1) / (STAGES.length - 1)) * 100}%` } })] }), _jsx("div", { className: "relative flex justify-between", children: STAGES.map((s, i) => {
                            const idx = i + 1;
                            const status = idx < current ? 'completed' : idx === current ? 'current' : 'pending';
                            return (_jsxs("div", { className: "flex flex-col items-center", style: { width: `${100 / STAGES.length}%` }, children: [_jsx("div", { className: `w-10 h-10 flex items-center justify-center rounded-full font-bold text-sm border-4 transition-all duration-300 ${status === 'completed'
                                            ? 'bg-green-500 border-green-500 text-white scale-100'
                                            : status === 'current'
                                                ? 'bg-blue-500 border-blue-500 text-white scale-110 shadow-lg animate-pulse'
                                                : 'bg-white border-gray-300 text-gray-400'}`, children: status === 'completed' ? '✓' : idx }), _jsx("div", { className: `text-xs mt-2 text-center font-medium max-w-20 ${status === 'completed' ? 'text-green-700' :
                                            status === 'current' ? 'text-blue-700' :
                                                'text-gray-400'}`, children: s })] }, s));
                        }) })] }), _jsxs("div", { className: "bg-gray-50 rounded-lg p-4 space-y-3", children: [_jsx("h3", { className: "font-semibold text-gray-800 mb-2", children: "Order Details" }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600", children: "Current Stage" }), _jsx("p", { className: "font-semibold text-gray-800", children: STAGES[current - 1] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600", children: "Items" }), _jsx("p", { className: "font-semibold text-gray-800", children: (order.items || []).join(', ') })] }), order.createdAt && (_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600", children: "Order Placed" }), _jsx("p", { className: "font-semibold text-gray-800", children: new Date(order.createdAt).toLocaleString() })] })), order.updatedAt && (_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600", children: "Last Updated" }), _jsx("p", { className: "font-semibold text-gray-800", children: new Date(order.updatedAt).toLocaleString() })] }))] })] }), _jsx("div", { className: "mt-6 text-center", children: current === 7 ? (_jsx("div", { className: "bg-green-50 border border-green-200 rounded-lg p-4", children: _jsx("p", { className: "text-green-800 font-semibold text-lg", children: "\uD83C\uDF89 Your order has been delivered!" }) })) : current >= 5 ? (_jsx("div", { className: "bg-blue-50 border border-blue-200 rounded-lg p-4", children: _jsx("p", { className: "text-blue-800 font-semibold", children: "\uD83D\uDCE6 Your order is on the way!" }) })) : (_jsx("div", { className: "bg-yellow-50 border border-yellow-200 rounded-lg p-4", children: _jsx("p", { className: "text-yellow-800 font-semibold", children: "\u23F3 Your order is being processed" }) })) })] }));
}
