import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { STAGE_NAMES } from '../../types';
export default function OrdersTable({ orders, onMoveToNextStage, onDelete, onMarkNotDelivered }) {
    const formatDate = (date) => {
        if (!date)
            return '-';
        return new Date(date).toLocaleString();
    };
    const getBuyerEmail = (order) => {
        if (typeof order.buyerId === 'object' && order.buyerId) {
            return order.buyerId.email || '-';
        }
        return '-';
    };
    return (_jsxs("div", { className: "overflow-auto bg-white rounded-lg shadow-lg", children: [_jsxs("table", { className: "min-w-full divide-y divide-gray-200", children: [_jsx("thead", { className: "bg-linear-to-r from-indigo-600 to-blue-500 text-white", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Order ID" }), _jsx("th", { className: "px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Stage" }), _jsx("th", { className: "px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Items" }), _jsx("th", { className: "px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Buyer Name" }), _jsx("th", { className: "px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Buyer Email" }), _jsx("th", { className: "px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Created At" }), _jsx("th", { className: "px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Updated At" }), _jsx("th", { className: "px-4 py-3 text-center text-xs font-semibold uppercase tracking-wider", children: "Actions" })] }) }), _jsx("tbody", { className: "bg-white divide-y divide-gray-200", children: orders.map((o) => (_jsxs("tr", { className: "hover:bg-gray-50 transition-colors", children: [_jsxs("td", { className: "px-4 py-3 text-sm font-mono text-gray-700", children: [o._id?.substring(0, 8), "..."] }), _jsx("td", { className: "px-4 py-3 text-sm", children: _jsx("span", { className: `px-2 py-1 rounded-full text-xs font-semibold ${o.currentStage === 7 ? 'bg-green-100 text-green-800' :
                                            o.currentStage >= 5 ? 'bg-blue-100 text-blue-800' :
                                                o.currentStage >= 3 ? 'bg-yellow-100 text-yellow-800' :
                                                    'bg-gray-100 text-gray-800'}`, children: STAGE_NAMES[o.currentStage - 1] ?? o.currentStage }) }), _jsx("td", { className: "px-4 py-3 text-sm text-gray-600", children: (o.items || []).join(', ') }), _jsx("td", { className: "px-4 py-3 text-sm text-gray-700", children: typeof o.buyerId === 'object' ? o.buyerId.name : (o.buyerId ?? '-') }), _jsx("td", { className: "px-4 py-3 text-sm text-gray-600", children: getBuyerEmail(o) }), _jsx("td", { className: "px-4 py-3 text-sm text-gray-500", children: formatDate(o.createdAt) }), _jsx("td", { className: "px-4 py-3 text-sm text-gray-500", children: formatDate(o.updatedAt) }), _jsx("td", { className: "px-4 py-3 text-sm text-center", children: _jsxs("div", { className: "flex gap-2 justify-center", children: [o.currentStage < 7 && (_jsx("button", { onClick: () => onMoveToNextStage(o._id), className: "px-3 py-1 bg-blue-600 hover:bg-blue-700 text-white rounded-md text-xs font-medium transition-colors", title: "Move to next stage", children: "Next Stage" })), o.currentStage === 7 && onMarkNotDelivered && (_jsx("button", { onClick: () => onMarkNotDelivered(o._id), className: "px-3 py-1 bg-orange-500 hover:bg-orange-600 text-white rounded-md text-xs font-medium transition-colors", title: "Mark as not delivered", children: "Not Delivered" })), _jsx("button", { onClick: () => onDelete(o._id), className: "px-3 py-1 bg-red-600 hover:bg-red-700 text-white rounded-md text-xs font-medium transition-colors", title: "Delete order", children: "Delete" })] }) })] }, o._id))) })] }), orders.length === 0 && (_jsx("div", { className: "text-center py-8 text-gray-500", children: "No orders found" }))] }));
}
