import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { STAGE_NAMES } from '../../types';
export default function OrdersTable({ orders, onAssociateBuyer, onViewDetails, onAssignSeller, onDelete }) {
    const formatDate = (date) => {
        if (!date)
            return '-';
        return new Date(date).toLocaleString();
    };
    const getUserInfo = (userRef, field) => {
        if (!userRef)
            return '-';
        if (typeof userRef === 'object') {
            if (field === 'id')
                return userRef._id || '-';
            return userRef[field] || '-';
        }
        return field === 'id' ? userRef : '-';
    };
    return (_jsxs("div", { className: "overflow-auto bg-white rounded-lg shadow-lg", children: [_jsxs("table", { className: "min-w-full divide-y divide-gray-200", children: [_jsx("thead", { className: "bg-linear-to-r from-purple-600 to-indigo-600 text-white", children: _jsxs("tr", { children: [_jsx("th", { className: "px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Order ID" }), _jsx("th", { className: "px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Stage" }), _jsx("th", { className: "px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Items" }), _jsx("th", { className: "px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Buyer Name" }), _jsx("th", { className: "px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Buyer ID" }), _jsx("th", { className: "px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Buyer Email" }), _jsx("th", { className: "px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Seller Name" }), _jsx("th", { className: "px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Seller ID" }), _jsx("th", { className: "px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Seller Email" }), _jsx("th", { className: "px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Created At" }), _jsx("th", { className: "px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider", children: "Updated At" }), _jsx("th", { className: "px-3 py-3 text-center text-xs font-semibold uppercase tracking-wider", children: "Actions" })] }) }), _jsx("tbody", { className: "bg-white divide-y divide-gray-200", children: (orders || []).map((o) => (_jsxs("tr", { className: "hover:bg-gray-50 transition-colors", children: [_jsxs("td", { className: "px-3 py-3 text-sm font-mono text-gray-700", children: [o._id?.substring(0, 8), "..."] }), _jsx("td", { className: "px-3 py-3 text-sm", children: _jsx("span", { className: `px-2 py-1 rounded-full text-xs font-semibold ${o.currentStage === 7 ? 'bg-green-100 text-green-800' :
                                            o.currentStage >= 5 ? 'bg-blue-100 text-blue-800' :
                                                o.currentStage >= 3 ? 'bg-yellow-100 text-yellow-800' :
                                                    'bg-gray-100 text-gray-800'}`, children: STAGE_NAMES[o.currentStage - 1] ?? o.currentStage }) }), _jsx("td", { className: "px-3 py-3 text-sm text-gray-600", children: (o.items || []).join(', ') }), _jsx("td", { className: "px-3 py-3 text-sm text-gray-700", children: getUserInfo(o.buyerId, 'name') }), _jsx("td", { className: "px-3 py-3 text-sm font-mono text-gray-500", children: getUserInfo(o.buyerId, 'id') }), _jsx("td", { className: "px-3 py-3 text-sm text-gray-600", children: getUserInfo(o.buyerId, 'email') }), _jsx("td", { className: "px-3 py-3 text-sm text-gray-700", children: getUserInfo(o.sellerId, 'name') }), _jsx("td", { className: "px-3 py-3 text-sm font-mono text-gray-500", children: getUserInfo(o.sellerId, 'id') }), _jsx("td", { className: "px-3 py-3 text-sm text-gray-600", children: getUserInfo(o.sellerId, 'email') }), _jsx("td", { className: "px-3 py-3 text-sm text-gray-500", children: formatDate(o.createdAt) }), _jsx("td", { className: "px-3 py-3 text-sm text-gray-500", children: formatDate(o.updatedAt) }), _jsx("td", { className: "px-3 py-3 text-sm", children: _jsxs("div", { className: "flex gap-1 justify-center flex-wrap", children: [_jsx("button", { onClick: () => onAssociateBuyer?.(o._id), className: "px-2 py-1 bg-yellow-500 hover:bg-yellow-600 text-white rounded text-xs font-medium transition-colors", title: "Associate buyer", children: "Associate" }), _jsx("button", { onClick: () => onAssignSeller?.(o._id), className: "px-2 py-1 bg-indigo-600 hover:bg-indigo-700 text-white rounded text-xs font-medium transition-colors", title: "Assign seller", children: "Assign Seller" }), _jsx("button", { onClick: () => onViewDetails?.(o._id), className: "px-2 py-1 bg-gray-600 hover:bg-gray-700 text-white rounded text-xs font-medium transition-colors", title: "View details", children: "Details" }), onDelete && (_jsx("button", { onClick: () => onDelete(o._id), className: "px-2 py-1 bg-red-600 hover:bg-red-700 text-white rounded text-xs font-medium transition-colors", title: "Delete order", children: "Delete" }))] }) })] }, o._id))) })] }), (!orders || orders.length === 0) && (_jsx("div", { className: "text-center py-8 text-gray-500", children: "No orders found" }))] }));
}
